[project]
name = "bubble-cosh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.13.15",
    "matplotlib>=3.10.3",
    "plotly>=6.1.2",
    "scipy>=1.15.3",
]
